### PR TITLE
fix: Improve `IsApiContractPresent` accuracy

### LINKED ISSUE #8537: `ApiInformation.IsApiContractPresent` is not accurate
### Current behavior

`IsApiContractPresent` does not accurately reflect reality.

### Expected behavior

Should be more accurate.

### How to reproduce it (as minimally and precisely as possible)

_No response_

### Workaround

_No response_

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

_No response_

### Affected platforms

iOS, Android, WebAssembly, WebAssembly renderers for Xamarin.Forms, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE

_No response_

### IDE version

_No response_

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by MartinZikmund**
GitHub Issue (If applicable): closes #8537 

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

- Version information in `IsApiContractPresent` is not up to date
- Additional supported contracts are not reported correctly

## What is the new behavior?

- Updated to 22000
- Additional contracts are correctly reported

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

### CODE REVIEW

File: src/Uno.UWPSyncGenerator/Program.cs [hunk 1]
```diff
@@ -33,6 +33,9 @@ static void Main(string[] args)
 				new SyncGenerator().Build(@"..\..\..\Uno.UWP", "Uno", "Windows.Networking.Connectivity.WwanContract");
 				new SyncGenerator().Build(@"..\..\..\Uno.UWP", "Uno", "Windows.ApplicationModel.Calls.CallsPhoneContract");
 
+				// When adding support for a new WinRT contract here, ensure to add it to the list of origins in Generator.cs
+				// and to the list of supported contracts in ApiInformation.shared.cs
```
Comment (Youssef1313) [inline src/Uno.UWPSyncGenerator/Program.cs:37]: Consider a `Debug.Fail` for the `default` case in ApiInformation.IsApiContractPresent

**Review by jeromelaban — APPROVED** [review]

**Review by ajpinedam — APPROVED** [review]
